/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 13 03:28:31 GMT 2019
 */

package com.saud_dev.technology_assessment.validators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.saud_dev.technology_assessment.validators.CustomerValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CustomerValidator_ESTest extends CustomerValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CustomerValidator.validateTimeAsCustomer("9");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        CustomerValidator.validateTimeAsCustomer("customer");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 400 BAD_REQUEST \"Invalid Parameter value for time_as_customer: customer\"; nested exception is java.lang.NumberFormatException: For input string: \"customer\"
         //
         verifyException("com.saud_dev.technology_assessment.validators.CustomerValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CustomerValidator.validateTimeAsCustomer((String) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CustomerValidator.validateCustomer("employee");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CustomerValidator.validateCustomer("customer");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CustomerValidator.validateCustomer("affiliate");
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        CustomerValidator.validateCustomer("A");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 400 BAD_REQUEST \"Invalid parameter for customer type: A\"
         //
         verifyException("com.saud_dev.technology_assessment.validators.CustomerValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        CustomerValidator.validateCustomer("");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 400 BAD_REQUEST \"Invalid parameter, customer cannot be empty\"
         //
         verifyException("com.saud_dev.technology_assessment.validators.CustomerValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      // Undeclared exception!
      try { 
        CustomerValidator.validateCustomer((String) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 400 BAD_REQUEST \"Invalid parameter, customer cannot be empty\"
         //
         verifyException("com.saud_dev.technology_assessment.validators.CustomerValidator", e);
      }
  }
}
