/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 14 17:26:42 GMT 2019
 */

package com.saud_dev.technology_assessment.validators;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;

import org.junit.Test;

import com.saud_dev.technology_assessment.model.item.Item;

public class ItemValidator_Test {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Item> linkedList0 = new LinkedList<Item>();
      Item item0 = new Item();
      item0.setValue("8D");
      linkedList0.add(item0);
      ItemValidator.validateItems(linkedList0);
      assertEquals(1, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Item> linkedList0 = new LinkedList<Item>();
      Item item0 = new Item();
      item0.setValue("");
      linkedList0.add(item0);
      // Undeclared exception!
      try { 
        ItemValidator.validateItems(linkedList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 400 BAD_REQUEST \"Invalid Parameter item value for item : null,\"; nested exception is java.lang.NumberFormatException: empty String
         //
         verifyException("com.saud_dev.technology_assessment.validators.ItemValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Item> linkedList0 = new LinkedList<Item>();
      Item item0 = new Item();
      List<Item> list0 = linkedList0.subList(0, 0);
      linkedList0.add(item0);
      // Undeclared exception!
      try { 
        ItemValidator.validateItems(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Item> linkedList0 = new LinkedList<Item>();
      Item item0 = new Item();
      linkedList0.add(item0);
      // Undeclared exception!
      try { 
        ItemValidator.validateItems(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
